nelmio_api_doc:
    documentation:
        info:
            title: Account-password backend system
            description: The end product consists of 3 endpoints signUp, login and verify email.
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc

